# Generated by Django 3.1.7 on 2021-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brafikk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brafikk',
            name='title',
            field=models.CharField(default='notitle', max_length=50),
        ),
        migrations.AlterField(
            model_name='brafikk',
            name='status',
            field=models.TextField(default='nostatus'),
        ),
    ]
